# Register a new user
POST http://localhost:8000/account/register
Content-Type: application/json

{
  "username": "fellowmonster",
  "password": "test"
}

###

# Login and get access token
POST http://localhost:8000/account/login
Content-Type: application/json

{
  "username": "fellowmonster",
  "password": "test"
}

###

# Access a protected endpoint using the access token
GET http://localhost:8000/account/token
Authorization: Bearer <access_token>
